alias "gpl=git pull -r --autostash"
alias "gps=git push"
alias "gch=git checkout"
alias "gcm=git commit -m"
alias "gs=git status"
alias "gd=git diff"
alias "gds=git diff --staged"
alias "gb=git branch"
alias "gba=git branch -a"
alias "gl=git log --graph"
alias "gla=gl --author"
alias "ga=git add"
alias "gr=git reset"
alias "gg=git grep"

